# Generated by Django 3.1.7 on 2021-08-21 02:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InstanceInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instance_type', models.CharField(max_length=8)),
                ('instance_name', models.CharField(max_length=36)),
                ('instance_configuration', models.JSONField(null=True)),
                ('instance_status', models.CharField(max_length=16)),
                ('apply_time', models.DateTimeField(null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'instance_info',
                'ordering': ('instance_name', 'apply_time'),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InstancePort',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('port', models.IntegerField()),
                ('status', models.CharField(default='free', max_length=10)),
                ('instance_info', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.instanceinfo')),
            ],
            options={
                'db_table': 'instance_port',
                'ordering': ('port',),
                'abstract': False,
            },
        ),
        migrations.AddIndex(
            model_name='instanceport',
            index=models.Index(fields=['port'], name='instance_po_port_3a46e4_idx'),
        ),
        migrations.AddIndex(
            model_name='instanceinfo',
            index=models.Index(fields=['instance_name'], name='instance_in_instanc_041b51_idx'),
        ),
    ]
